name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    # Runs at the top of the hour, every 12 hours
    - cron: "0 */12 * * *" 
  
  workflow_dispatch: # Allows manual trigger from the Actions tab

  push:
    branches:
    - main # Trigger on push to main branch

jobs:
  generate:
    # IMPORTANT: The token needs write access to the contents of the repo.
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 1. Generate the SVG image using the action
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main 
        with:
          # Uses your GitHub username detected automatically
          github_user_name: ${{ github.repository_owner }}
      
      # 2. COMMIT FIX: Use the reliable EndBug action to commit the generated file
      - name: Commit and Push Pacman Graph
        # Using a proven, reliable alternative action
        uses: EndBug/add-and-commit@v9 
        with:
          message: "chore: Updated Pac-Man Contribution Graph (Fix)"
          # Commits both the dark and light mode SVG files
          add: 'pacman-contribution-graph*.svg' 
